{"name": "Ошибка, при создании курьера с занятым логином", "status": "passed", "start": 1717365855650, "stop": 1717365855851, "uuid": "8961fdd1-62f5-446b-a9f9-652e9fe2848c", "historyId": "9c1462b9d23eb2fd2dc889d029ad3343", "testCaseId": "9c1462b9d23eb2fd2dc889d029ad3343", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_courier_with_existing_login_error_409", "labels": [{"name": "story", "value": "Создание курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "Rayless"}, {"name": "thread", "value": "86020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}