{"name": "Ошибка, при создании курьера с пустым обязательным полем", "status": "broken", "statusDetails": {"message": "TypeError: 'dict' object is not callable", "trace": "self = <tests.test_create_courier.TestCreateCourier object at 0x0000019A6A4343D0>, create_new_courier = {'firstName': 'tqsdmybvjw', 'login': 'hutbmtaicl', 'password': 'trmbehhgnb'}\n\n    @allure.title(\"Ошибка, при создании курьера с пустым обязательным полем\")\n    def test_create_courier_with_null_login_error_400(self, create_new_courier):\n>       payload = create_new_courier(10)\nE       TypeError: 'dict' object is not callable\n\ntests\\test_create_courier.py:22: TypeError"}, "start": 1717365856060, "stop": 1717365856060, "uuid": "6cec889d-4d4b-48f5-94bb-53844f991483", "historyId": "6d12d9da8e6ce0466cb9eca08852569c", "testCaseId": "6d12d9da8e6ce0466cb9eca08852569c", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_courier_with_null_login_error_400", "labels": [{"name": "story", "value": "Создание курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "Rayless"}, {"name": "thread", "value": "86020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}